### ISSUE TITLE
How to determine white space?

### ISSUE THREAD

**Issue by mmlkvch** [laravie/parser#20]
I got all W content inside the Primitive now my problem is how to determine the L(also others) and treat it as space true or false.

I want to have output similar to this:

[0] => Array
                (
                    [content] => Array
                        (
                            [0] => Array
                                (
                                    [word] => NEWLINE /** treat for empty field**/
                                )
                            [1] => Array
                                (
                                    [word] => EXCLUSIVE
                                )

                            [2] => Array
                                (
                                    [word] => :
                                )

                            [3] => Array
                                (
                                    [word] => Soldiers
                                )

                            [4] => Array
                                (
                                    [word] => told
                                )

                            [5] => Array
                                (
                                    [word] => words
                                )

                            [6] => Array
                                (
                                    [word] => like
                                )

                            [7] => Array
                                (
                                    [word] => NEWLINE /** treat for empty field**/
                                )

See image below for the XML that I currently extracting data:

![image](https://user-images.githubusercontent.com/38088639/47273869-b1564380-d5ce-11e8-96e5-016b657c1db3.png)

**Comment by crynobone** [comment]
I don't think the parser was design to handle this.
