### ISSUE TITLE
Question: How to handle a pair of particular cases of nested nodes

### ISSUE THREAD

**Issue by LucaColombi** [laravie/parser#24]
Hello,

I need to handle this:
```
<nodes>
<node>
<!-- first question, how to make all this at same level -->
      <Data>data</Data>
      <NestedData>
        <NestedA>na</NestedA>
        <NestedB>nb</NestedB>
      </NestedData>

<!-- second question, some way to handle this kind of multiple repetition without loosing data and grouping if possible -->
    <RepeatedMixedData>

      <RepeatedA>ra1</RepeatedA>
      <RepeatedB>rb1</RepeatedB>

      <RepeatedA>ra2</RepeatedA>
      <RepeatedB>rb2</RepeatedB>

    </RepeatedMixedData>
</node>
</nodes>
```

performing 2 operations: extract nested at parent level (NestedA will be pair with Data), and grouping repeated subnodes (maybe this is not possible?), the result should be something like this:
```
...[
    Data=>'data',
    NestedA=>'na',
    NestedB=>'nb'


    RepeatedMixedData=>[[
        'RepeatedA'=>'ra1',
        'RepeatedB'=>'rb1',
    ],[
        'RepeatedA'=>'ra2',
        'RepeatedB'=>'rb2',
    ],
//OR
    [
        'RepeatedA'=>['ra1','ra2],
        'RepeatedB'=>['rb1','rb2']
    ],
    ]
]
```

is there a solution for both, or at least one?

Thank you in advance

**Comment by taunoM** [comment]
I have something similar and i would like to know the answer aswell. In my case i have:
`<transport>
    <items>
        <item code="1111" name="Some name" class="class_name">
        <data code="V1" content="C1"/>
        <data code="V2" content="C2"/>
        <data code="V3" content="C3" param="P3"/>
        <stocklevels>
        <stocklevel stock="AA" level="1"/>
        </stocklevels>
    </item>
</transport>`

Have tried many different approaches but none of them worked. I can get item info and it works well, i just cant understand how do i get data and stocklevels.

**Comment by crynobone** [comment]
<img width="1792" alt="Screenshot 2020-04-08 at 9 17 24 PM" src="https://user-images.githubusercontent.com/172966/78788432-6278b580-79de-11ea-81ae-9f37ddfdf61d.png">
