### ISSUE TITLE
The Error "Unable to parse XML from string" Is Not Accurate

### ISSUE THREAD

**Issue by Blair2004** [laravie/parser#28]
- Package Version: 5.0
- PHP Version: 7.3

### Description:
Recently I've updated Ubuntu to 19.04 where php7.3 has been set as default CLI PHP version. I've therefore started using a package I'm working on every day and suddenly I've been facing "Unable to parse XML from string". I tried to understand if the XML parsed was incorrect, so I've explored many XML validators online without any relevant results as the document was valid. I was forced to jump into the package code and catch the error here https://github.com/laravie/parser/blob/master/src/Xml/Reader.php#L21 Which pointed that "simplexml_load_string" function doesn't exist therefore I've quickly guessed that it's because the XML Package might be missing from PHP.

### Solution
We should have more than the error provided by default a clear hint that points relevant information that might be helpful.

**Comment by crynobone** [comment]
> We should have more than the error provided by default a clear hint that points relevant information that might be helpful.

I would say that *"simplexml_load_string" function doesn't exist* is a clear indication of the problem, plus this error is coming from PHP.
