### ISSUE TITLE
child attribute

### ISSUE THREAD

**Issue by alexgiuvara** [laravie/parser#4]
Hello,

I'm trying to use your class, but I encounter a problem for children attributes

```
<api>
    <user followers="5">
        <id>1</id>
        <email child_attribute="someValue">crynobone@gmail.com</email>
    </user>
</api>
```

My problem is that 'child_attribute' is never read as intended
```
$user = $xml->parse([
    'id' => ['uses' => 'user.id'],
    'email' => ['uses' => 'user.email'],
    'followers' => ['uses' => 'user::followers'],
    'child_attribute' => ['uses' => 'user.email::child_attribute'],
]);
```

This part '  'child_attribute' => ['uses' => 'user.email::child_attribute'],' does not work

Could you please tell me what I'm doing wrong, or where I can change your code for this functionality ?

Thank you,
Alex

**Comment by crynobone** [comment]
Just added additional example, test are passing on my end.
