### ISSUE TITLE
composer issue

### ISSUE THREAD

**Issue by michabbb** [laravie/parser#8]
dear @crynobone , because of my merge request, i have a problem here, maybe you can bring light into this...

when i install your package: `composer require "laravie/parser=~1.0"`

i end up with the following versions (composer show):

```
illuminate/contracts                dev-master 1cc9ce9        The Illuminate Contracts package.
illuminate/support                  dev-master fcaaaeb        The Illuminate Support package.
laravie/parser                      dev-master 87fe17e        XML Document Parser for PHP
```

and because "dev-master" gets installed, i end up in a problem that illuminate/support only support php7.

shouldn´t i see here "5.1" or something like that ?

thanks for any help.

**Comment by michabbb** [comment]
okay, super strange, i have to find out why.... there seems to be a problem with the [docker version of composer](https://github.com/composer/docker).... when i use an older version of composer it get:

```
illuminate/contracts                5.4.x-dev 68569e8         The Illuminate Contracts package.
illuminate/support                  5.4.x-dev 6aa05cb         The Illuminate Support package.
```

and this is how it should look like (i guess).

**Comment by crynobone** [comment]
https://travis-ci.org/laravie/parser

We are testing this package against PHP 5.5, 5.6, 7.0, 7.1, 7.2 and HHVM. If any of the combination is incompatible the tests would fail.

**Comment by michabbb** [comment]
in case someone is using composer with docker, i hope to find the answere [here](https://github.com/composer/docker/issues/18).
