### ISSUE TITLE
Misleading error when file does not exists.

### ISSUE THREAD

**Issue by lracicot** [laravie/parser#9]
## Description
I used the library and I got the following error: "Unable to parse XML from string.". I did not understand why I got this error because I know that my file contains valid XML, until I removed the `@` symbol in front of  `@simplexml_load_file(...)`.

## Expected result
I expect to have a better error for a common error like a wrong file path, such as:
```
Could not file the file ${file_path}
```

## Actual result
```
Unable to parse XML from string.
```

which is not very true, because the actual variable is null.

## Suggestion
I would suggest to first check if the file exist before calling `@simplexml_load_file(...)` and handle the error properly.

**Reader.php**
```
public function load($filename)
{
    if (!file_exists($filename)) {
        throw new FileNotFoundException('Could not file the file ' . $filename);
    }

    $xml = @simplexml_load_file($filename);

    return $this->resolveXmlObject($xml);
}
```

**FileNotFoundException.php**
```
class FileNotFoundException extends \InvalidArgumentException
{
    //
}
```

I would be happy to send you a pull request to address this issue if you agree with my suggestion.

**Comment by crynobone** [comment]
Send a PR.
